### ISSUE TITLE
not working on latest pm2

### ISSUE THREAD

**Issue by hoseininjast** [4xmen/pm2panel#9]
hi
im trying to use this tool but in npm install i get error :
```
npm error code 1
npm error path /root/pm2panel/node_modules/node-linux-pam
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.14.0 | linux | x64
npm error gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/root/pm2panel/node_modules/node-linux-pam/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/root/.cache/node-gyp/20.14.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.14.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.14.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/root/pm2panel/node_modules/node-linux-pam',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: not found: make
npm error gyp ERR! stack at getNotFoundError (/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
npm error gyp ERR! stack at which (/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
npm error gyp ERR! stack at async doWhich (/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
npm error gyp ERR! stack at async loadConfigGypi (/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
npm error gyp ERR! stack at async build (/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
npm error gyp ERR! stack at async run (/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Linux 5.15.0-67-generic
npm error gyp ERR! command "/root/.nvm/versions/node/v20.14.0/bin/node" "/root/.nvm/versions/node/v20.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /root/pm2panel/node_modules/node-linux-pam
npm error gyp ERR! node -v v20.14.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok

npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-08T18_39_51_124Z-debug-0.log
```

i have tried to installing the libpam0g-dev but its get this error after installing it.
os : ubuntu 24
node : v20.14.0
npm : 10.7.0

**Comment by SagePtr** [comment]
You need `apt install build-essential` as well
